### ISSUE TITLE
panic and hang: unreachable reached

### ISSUE THREAD

**Issue by ggwpez** [HigherOrderCO/hvm-lang#109]
Tested on `hvml` master commit 89b0c80673caeba9745794e60f9c671a44e1a01d. Panics:  
```pre
Main = (+ λx(x) 1)
```

I understand that this is not correctly typed, but could it maybe print a proper error message? I had to reduce my expression by hand multiple steps to understand what the issue was.

Now the above code only panics and crashes, but it can also be made to hang indefenitely:  
```pre
Main = (+ λfλx(x) 1)
```

**Comment by developedby** [comment]
It does print a message before panicking, but it's a bit cryptic. https://github.com/HigherOrderCO/hvm-core/pull/53 this PR makes it more explicit what is the problem with your program.

The second program should also be crashing. Running the compilation output with `hvmc` crashes as I expected, so there seems to be some compiler bug in the second example.

**Comment by developedby** [comment]
What information would you like to be displayed in the error message?

The program that crashes doesn't have a valid readback on hvm-lang, but we could possibly print the inet before the invalid reduction.

**Comment by ggwpez** [comment]
Thanks for the quick reply!  

>What information would you like to be displayed in the error message?

`Function '+' cannot be applied with arguments (Lam, Num). Only (Num, Num) are valid.` or something like this? Dont know if its possible at all though, since this seems like a low level machine.

**Comment by developedby** [comment]
That will come when we write the type checker for hvml (very soon).

For the runtime underneath, an invalid interaction is like an invalid opcode in a VM. And it's even harder to know exactly what was the origin since data and instructions are the same thing, after a function is applied we lose all information about the source of that inet.

**Comment by developedby** [comment]
You can try running the program in debug mode `hvml run <file> -d` to see the step by step execution, could help you to find the source of errors like this

**Comment by ggwpez** [comment]
> That will come when we write the type checker for hvml (very soon).

Nice, looking forward to that.

> If this happens in the future (before the type-checker), you can also try running the program in debug mode hvml run <file> -d to see the step by step execution, could help you to find the source of errors like this

I will try that, many thanks for this awesome project!

So i guess before the type checker it will just stay as-is? Module your MR to make the panic message a bit more helpful. Then we can close i guess.

**Comment by developedby** [comment]
Closed by https://github.com/HigherOrderCO/hvm-core/pull/60
