### ISSUE TITLE
panicked at 'internal error: entered unreachable code

### ISSUE THREAD

**Issue by tromp** [HigherOrderCO/hvm-lang#58]
I = λx x
T = λx λy x
L = λn (λz (z T (L (I n))))
Main = (T I (L I)) 

when run produces

$ hvml run bug2.hvm 
0105d8e00105d8df 010166cc0105d8e1
thread '<unnamed>' panicked at 'internal error: entered unreachable code', /Users/tromp/.cargo/git/checkouts/hvm-core-31580e46fc731f4f/013c775/src/run.rs:690:67
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

When changing L to either
  L = λn (λz (z T (L n)))
or
  L = λn (λz (z n (L (I n))))
it instead hangs (or loops forever).

**Comment by imaqtkatt** [comment]
I think this program loops forever because it's not possible to extract `L` into a supercombinator so it will expand infinitely.

If i define `L` like this it should work:
```haskell
L = λself λn (λz (z T (self (I n))))
Main = (T I (L L I))
```

**Comment by tromp** [comment]
The program should just return (T I (L L I)) = I.
It's an if True then I else L I so what L does should be irrelevant.

Btw, this is a trimmed down version of a prime number sieve where L is an infinite list of booleans, that gives the same error:

B0 = λx λy x
B1 = λx λy y
K = B0
Nil = B1
Cons = λx λy λz (z x y)
Cons0 = (Cons B0)
Two = λb λc (b (b c))
Three = λb λc (b (b (b c)))
Four = λb λc (b (b (b (b c))))
Y = λf ((λx (x x)) (λx (f (x x))))
S0    = λcont  λx λxs (Cons0  (xs cont))
Ssucc = λSn λc λx λxs (Cons x (xs (Sn c)))
Sieve = λSn (Cons B1 ((λSsn (Sieve Ssn (Y Ssn))) (Ssucc Sn)))
Primes = (Cons0 (Cons0 (Sieve S0)))
Take = λcont λx λxs λz (z x (xs cont))
Main = (Primes (Four Take (K (K Nil))))

**Comment by imaqtkatt** [comment]
You're right, this program returns the identity function. But since the runtime is eager, `(L I)` will not be ignored and the problem I commented will occur

**Comment by tromp** [comment]
How does program lazy constructs then?
Such as is necessary for if-then-else?

**Comment by developedby** [comment]
You can do it as long as your recursive functions are not directly being called in themselves (or similar more complicated recursive patterns).

For example, you can write an if function like this:
```
false = λx λy x
true = λx λy y
if = λx λthen λelse (x then else)
```
Then, if your function needs to take an argument, you pass it later, to keep the lazyness:
```
is_zero = λn match n {0: true; 1+*: false}
is_even = λn ((if (is_zero n) (λ* true) is_odd) (- n 1))
is_odd = λn ((if (is_zero n) (λ* false) is_even) (- n 1))
```
Notice how here we need an additional `λ` compared to what we might write for a lazy evaluator
```
is_even = λn (if (is_zero n) true (is_odd (- n 1)))
```

**Comment by developedby** [comment]
In general, as long as the recursive part is written as a combinator, it will work fine

**Comment by tromp** [comment]
Ok; why does this one panic then?

K = λx λy x
Nil = λx λy y
Cons = λx λy λz (z x y)
Fib = λa λb (Cons a (λz (Fib b (+ a b))))
Main = (Fib 0 1 K)

I stuck an extra λ into Fib to allow eager evaluation.
